package config

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"gopkg.in/yaml.v3"
)

const (
	configFileName = "config.yaml"
	appName        = "zte-cli"
)

// Config holds all application configuration.
type Config struct {
	RouterHost     string `yaml:"router_host"`
	RouterUsername string `yaml:"router_username"`
	RouterPassword string `yaml:"router_password"`

	// Post-MVP: Telegram Bot settings
	TelegramToken  string `yaml:"telegram_token"`
	TelegramChatID int64  `yaml:"telegram_whitelist_chat_id"`
	CheckInterval  int    `yaml:"check_interval_seconds"`
}

// DefaultConfig returns a Config with sensible defaults.
func DefaultConfig() *Config {
	return &Config{
		RouterHost:     "192.168.100.1",
		RouterUsername: "admin",
		RouterPassword: "admin",
		TelegramToken:  "",
		TelegramChatID: 0,
		CheckInterval:  30,
	}
}

// Load searches for config.yaml in priority order and loads it:
// 1. ./config.yaml (current directory)
// 2. ~/.config/zte-cli/config.yaml (user home)
// 3. /etc/zte-cli/config.yaml (system)
func Load() (*Config, string, error) {
	paths := searchPaths()

	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			data, err := os.ReadFile(p)
			if err != nil {
				return nil, p, fmt.Errorf("failed to read config at %s: %w", p, err)
			}

			cfg := DefaultConfig()
			if err := yaml.Unmarshal(data, cfg); err != nil {
				return nil, p, fmt.Errorf("failed to parse config at %s: %w", p, err)
			}

			return cfg, p, nil
		}
	}

	return nil, "", fmt.Errorf("no config file found, run 'zte-cli config init' to create one")
}

// Init creates a template config.yaml at the user's config directory.
func Init() (string, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("could not determine home directory: %w", err)
	}

	configDir := filepath.Join(homeDir, ".config", appName)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return "", fmt.Errorf("could not create config directory: %w", err)
	}

	configPath := filepath.Join(configDir, configFileName)

	// Check if file already exists
	if _, err := os.Stat(configPath); err == nil {
		return configPath, fmt.Errorf("config file already exists at %s", configPath)
	}

	template := `# =========================================================
# zte-cli Configuration
# =========================================================
# This file was generated by: zte-cli config init
# Edit the values below to match your setup.

# --- Router Settings ---
router_host: "192.168.100.1"
router_username: "admin"
router_password: "admin"

# --- Telegram Bot (Post-MVP, leave empty for now) ---
# Get your bot token from @BotFather on Telegram
# Get your chat ID from @userinfobot on Telegram
telegram_token: ""
telegram_whitelist_chat_id: 0

# --- Monitoring ---
# How often to check internet connectivity (seconds)
check_interval_seconds: 30
`

	if err := os.WriteFile(configPath, []byte(template), 0644); err != nil {
		return "", fmt.Errorf("could not write config file: %w", err)
	}

	return configPath, nil
}

// Path returns the first config path that exists, or the recommended path.
func Path() string {
	paths := searchPaths()
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}

	homeDir, _ := os.UserHomeDir()
	return filepath.Join(homeDir, ".config", appName, configFileName)
}

// searchPaths returns the list of config file paths to check, in priority order.
func searchPaths() []string {
	paths := []string{
		configFileName, // ./config.yaml (current directory)
	}

	// User home config directory
	homeDir, err := os.UserHomeDir()
	if err == nil {
		xdgConfig := os.Getenv("XDG_CONFIG_HOME")
		if xdgConfig == "" {
			xdgConfig = filepath.Join(homeDir, ".config")
		}
		paths = append(paths, filepath.Join(xdgConfig, appName, configFileName))
	}

	// System config (Linux/macOS only)
	if runtime.GOOS != "windows" {
		paths = append(paths, filepath.Join("/etc", appName, configFileName))
	}

	return paths
}
